version: "3.9"

services:
  proto-tipo-frontend:
    build:
      context: ./Prototipo/proto-tipo
      dockerfile: Dockerfile
    container_name: proto-tipo-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
