version: "3.9"

services:
  tradar-chatbot:
    build: .
    container_name: tradar-chatbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Persistencia de la base de datos SQLite
      - ./data:/app/data

      # Cache de HuggingFace (evita re-descargar modelos)
      - ~/.cache/huggingface:/root/.cache/huggingface

    restart: unless-stopped
